http:
  host: 'localhost'
  port: 3000

db:
  couch-db:
    -

security:
  jwt:
    secret: 'secret'
    expires-in: '30m'
    refresh:
      secret: 'refresh'
      expires-in: '7 days'

log:
  level:
    - 'log'
    - 'error'
    - 'warn'
    - 'debug'
    - 'verbose'
