http:
  host: 'localhost'
  port: 3000

db:
  mongo:
    url: 'mongodb://localhost/hbs'

security:
  jwt:
    secret: 'secret'
    expires-in: '1h'

log:
  level:
    - 'log'
    - 'error'
    - 'warn'
    - 'debug'
    - 'verbose'
